dist: trusty
sudo: require
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - python3
      - python3-pip

install:
  - sudo pip3 install pytest
  - sudo pip3 install .

script:
  - python3 -m pytest test/test.py
