sudo: false
language: python
python: 3.5

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - cmake
            - cmake-data
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - g++ --version
  - pip3 install pytest
  - pip3 install .

script:
  - python3 -m pytest test/test.py
